"""Initial

Revision ID: 1d9813edcf35
Revises: 8e508fd30848
Create Date: 2022-01-17 12:32:19.455655

"""

# revision identifiers, used by Alembic.
revision = '1d9813edcf35'
down_revision = '8e508fd30848'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
